from enum import Enum

class Shape(Enum):
    BOX = "box"
    POLYGON = "polygon"
    ELLIPSE = "ellipse"
    OVAL = "oval"
    CIRCLE = "circle"
    POINT = "point"
    EGG = "egg"
    TRIANGLE = "triangle"
    PLAINTEXT = "plaintext"
    PLAIN = "plain"
    DIAMOND = "diamond"
    TRAPEZIUM = "trapezium"
    PARALLELOGRAM = "parallelogram"
    HOUSE = "house"
    PENTAGON = "pentagon"
    HEXAGON = "hexagon"
    SEPTAGON = "septagon"
    OCTAGON = "octagon"
    DOUBLECIRCLE = "doublecircle"
    DOUBLEOCTAGON = "doubleoctagon"
    TRIPLEOCTAGON = "tripleoctagon"
    INVTRIANGLE = "invtriangle"
    INVTRAPEZIUM = "invtrapezium"
    INVHOUSE = "invhouse"
    MDIAMOND = "Mdiamond"
    MSQUARE = "Msquare"
    MCIRCLE = "Mcircle"
    RECT = "rect"
    RECTANGLE = "rectangle"
    SQUARE = "square"
    STAR = "star"
    NONE = "none"